# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%pip install mdutils
%run initialise.py

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


FileNotFoundError: [Errno 2] No such file or directory: 'source\\headers.ktx'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
np.show_config()

1.26.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2952636600240
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.2
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.5
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
null_vec = np.zeros(10)
print(null_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [13]:
z = np.zeros((10,10))
print(z)
z.size
print(f"The memory usage is {z.size*z.itemsize}")

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
The memory usage is 800


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [24]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [26]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [28]:
V = np.arange(10,50)
print(V)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [34]:
V = V[::-1]
print(V)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [37]:
M = np.arange(9).reshape(3,3)
print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [40]:
A = [1,2,0,0,4,0]
print(np.nonzero(A))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [41]:
M = np.eye(3,3)
print(M)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [45]:
A = np.random.random((3,3,3))
print(A)

[[[0.21528303 0.39883196 0.89278084]
  [0.82000826 0.60213368 0.04754289]
  [0.59825735 0.97322668 0.35578114]]

 [[0.02919727 0.53909073 0.50377758]
  [0.59678566 0.8008765  0.00150934]
  [0.21804332 0.45496721 0.2080379 ]]

 [[0.14688985 0.44114614 0.4308786 ]
  [0.03427012 0.14314519 0.36604373]
  [0.87355455 0.94803051 0.39067113]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [54]:
A = np.random.random((10,10))
mx, min = A.max(), A.min()
print(mx, min)

0.9984798732972272 0.0019065162802405222


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [58]:
V = np.random.random(30)
men = np.average(V)
alt_men = V.mean()
print(men,alt_men)

0.5566310864614948 0.5566310864614948


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [64]:
def bordered_array(m,n=None):
    if n == None:
        n = M
    A = np.ones((m,n))
    A[1:-1,1:-1] = 0
    return A

print(bordered_array(4,4))

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [71]:
A = np.ones((3,3))
B = np.pad(A, pad_width=1, mode='constant', constant_values=0)
print(B)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [72]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

np.nan
False
False
np.nan
True
False

nan
False
False
nan
True
False


True

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [76]:
A = np.diag([1,2,3,4])
A = np.pad(A,((1,0),(0,1)),mode="constant",constant_values=0)
print(A)

Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [81]:
A = np.zeros((8,8),dtype=int)
A[1::2,::2] = 1
A[::2,1::2] = 1
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [87]:
print(np.unravel_index(99,(6,7,8)))
print(np.ravel_multi_index((1,5,3),(6,7,8)))

(1, 5, 3)
99


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [91]:
A = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [95]:
M = np.random.random((5,5))
M = (M-M.mean())/M.std()
print(M)

[[-1.02632711  1.05833817 -1.17217001 -1.10717693 -0.9325699 ]
 [ 0.0520296  -2.46122745 -0.7433711   1.05799794  1.07893783]
 [-0.40361231  1.14531597  0.04667635  0.59661056 -1.53895875]
 [-0.41828814  1.22197868  1.43300662  0.47508255  0.02094092]
 [-0.7392145   0.33555478  0.26282784  1.01828761  0.73933078]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [97]:
colors = np.dtype([('r',np.ubyte),
                   ('g',np.ubyte),
                   ('b',np.ubyte),
                   ('a',np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [101]:
A = np.ones((5,3))
B = np.ones((3,2))
print(np.dot(A,B))
print(np.matmul(A,B))
print(A@B)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [106]:
A = np.arange(11)
A[ (A>3) & (A<8)] *= -1
print(A)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
#Done

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [108]:
#Yes, No, No, Ues, Yes, No?
Z = np.arange(1,6)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [109]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\kawil\AppData\Local\Temp\ipykernel_2916\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\kawil\AppData\Local\Temp\ipykernel_2916\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\kawil\AppData\Local\Temp\ipykernel_2916\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [120]:
A = np.random.uniform(-5,5,10)
print(A)
A = np.copysign(np.ceil(np.abs(A)), A)
print(A)

[-0.41613575  0.88477243  4.36728048 -1.24105003 -4.7032845  -4.16444024
  0.69241427  2.67873692 -4.95049928 -2.96785206]
[-1.  1.  5. -2. -5. -5.  1.  3. -5. -3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [126]:
A = np.random.randint(1,11,10)
B = np.random.randint(1,11,10)
print(np.intersect1d(A,B))
print(A)
print(B)

[4 6 9]
[6 9 9 1 4 8 5 5 1 8]
[6 4 2 6 6 6 9 9 2 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [140]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
print(Z)
#back to sanity
_ = np.seterr(**defaults)
Z = np.ones(1) / 0
print(Z)

[inf]
[inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [141]:
#False?
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [145]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1,'D')
print(yesterday,today,tomorrow)

2024-09-30 2024-10-01 2024-10-02


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [147]:
july2016 = np.arange(np.datetime64('2016-07'),np.datetime64('2016-08'),dtype='datetime64[D]')
print(july2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [155]:
A = np.arange(11,dtype="float64")
B = np.arange(11,22,dtype="float64")
print( (A+B)*(-A/2)   )
np.add(A,B,out = B)
np.divide(A,2,out = A)
np.negative(A,out = A)
np.multiply(A,B,out = A)
print(A)

[  -0.    -6.5  -15.   -25.5  -38.   -52.5  -69.   -87.5 -108.  -130.5
 -155. ]
[  -0.    -6.5  -15.   -25.5  -38.   -52.5  -69.   -87.5 -108.  -130.5
 -155. ]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [160]:
A = np.random.uniform(0,10,10)

B = np.floor(A)
C = A - A % 1
F = A//1
D = A.astype('int')
E = np.trunc(A)

print(A,B,C,D,E,F)

[4.68066029 9.38373403 9.39377415 6.60816221 5.80862605 2.52536173
 8.4252543  8.33469684 6.05223948 7.03810355] [4. 9. 9. 6. 5. 2. 8. 8. 6. 7.] [4. 9. 9. 6. 5. 2. 8. 8. 6. 7.] [4 9 9 6 5 2 8 8 6 7] [4. 9. 9. 6. 5. 2. 8. 8. 6. 7.] [4. 9. 9. 6. 5. 2. 8. 8. 6. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [162]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [6]:
def generate():
    for x in range(10):
        yield x

Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [10]:
V = np.linspace(0,1,11,endpoint=False)[1:]
print(V)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [11]:
V = np.random.random(10)
V.sort()
print(V)

[0.22059097 0.25511017 0.3418424  0.47654965 0.61361974 0.63996309
 0.69153339 0.77919919 0.79768419 0.9506578 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [13]:
Z = np.random.random(10)
print(np.add.reduce(Z))

5.760587082858623


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [24]:
A = np.random.random(10)
B = np.random.random(10)

print(np.allclose(A,B))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [29]:
A = np.arange(10)
A.flags.writeable = False
A.flags.writeable = True
A[2] = 4

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [36]:
A = np.random.random((10,2))
X,Y = A[:,0], A[:,1]
R = np.sqrt(X**2+Y**2)
Theta = np.arctan2(Y,X)
B = np.column_stack((R,Theta))
print(B)
print(R, Theta)


[[0.32178201 1.52713976]
 [1.03264781 0.39116719]
 [1.2118615  0.71551963]
 [0.6027696  0.4637303 ]
 [1.15127859 0.85373577]
 [1.2587154  0.78103717]
 [1.11607772 0.7448969 ]
 [0.65056867 0.04819356]
 [0.38336174 0.52376978]
 [0.20734019 0.02883655]]
[0.32178201 1.03264781 1.2118615  0.6027696  1.15127859 1.2587154
 1.11607772 0.65056867 0.38336174 0.20734019] [1.52713976 0.39116719 0.71551963 0.4637303  0.85373577 0.78103717
 0.7448969  0.04819356 0.52376978 0.02883655]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [40]:
A = np.random.random(10)
print(A)
A[A.argmax()] = 0
print(A)

[0.0589585  0.46107342 0.178513   0.23827899 0.34286086 0.83069302
 0.93872857 0.41150062 0.32715221 0.73939748]
[0.0589585  0.46107342 0.178513   0.23827899 0.34286086 0.83069302
 0.         0.41150062 0.32715221 0.73939748]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [48]:
A = np.zeros((5,5), [('x',float),('y',float)])
A['x'], A['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(A)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [53]:
A = np.random.random(10)
B = np.random.random(10)
A = A[:,np.newaxis]

C = 1/(A-B)

C_2 = 1.0 / np.subtract.outer(A[:,0],B)
print(np.linalg.det(C))
print(np.linalg.det(C_2))
print(C)

4422897674338.712
4422897674338.712
[[   2.62406167    1.44163734    1.81402461  -21.4339989     6.32361496
   -11.38864548   -5.84349199   16.81568104    1.24533333    2.29028788]
 [   1.97943702    1.22285076    1.48067866   12.91143998    3.54304699
    27.54912757  -21.26528192    5.44739905    1.07862833    1.78338353]
 [  -5.06080528    8.69791261  -36.46284481   -1.59912888   -2.3778486
    -1.50039227   -1.33366023   -1.92597583    4.45807143   -7.03931474]
 [   2.13746343    1.28137546    1.56735858   24.93715372    4.08341514
  -951.38661338  -11.85186687    6.83882453    1.12390677    1.91065038]
 [ -39.18586931    3.48374129    6.91312269   -2.20622533   -4.02462082
    -2.02259333   -1.73088672   -2.88068458    2.52276893   33.31298361]
 [   2.28362528    1.33250303    1.64454197   98.45660613    4.65226626
   -32.26311622   -8.74745676    8.5999378     1.16304837    2.02659729]
 [ -19.31709376    3.83436313    8.44564549   -2.08545756   -3.64008538
    -1.92062819   -1.65

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [58]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [70]:
A = np.arange(-50,50)
np.set_printoptions()
print(A)

[-50 -49 -48 ...  47  48  49]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [74]:
V = np.random.random(10)
target = 0.5
W = V-0.5
print(V)
print(V[np.argmin(np.abs(V-target))])


[0.33724991 0.44611186 0.06423322 0.03729751 0.99390601 0.99972056
 0.35052571 0.02207648 0.4951204  0.32445963]
0.49512040023208137


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [10]:
A = np.array(((0,0),(0,10,20)), dtype=[
    ('position', [('x',float, 1),
                  ('y',float)]),
    ('color', [('r',float),
               ('g',float),
               ('b',float)])])
print(A)

((0., 0.), (0., 10., 20.))


C:\Users\kawil\AppData\Local\Temp\ipykernel_30752\4275176393.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  A = np.array(((0,0),(0,10,20)), dtype=[


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [19]:
A = np.random.random((100,2))
X,Y = A[:,0], A[:,1]
D_x = X[:,np.newaxis] - X
D_y = Y[:,np.newaxis] - Y
D = np.sqrt(D_x**2 + D_y**2)


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [23]:
A = np.ones(10)
A = A.astype("int32")


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [29]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
A = np.genfromtxt(s, delimiter=",", dtype=int,filling_values=0)
print(A)

[[ 1  2  3  4  5]
 [ 6  0  0  7  8]
 [ 0  0  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [30]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [31]:
A = np.random.normal(size = (10,10))
print(A)

[[-1.68227307  1.90582889 -1.23167297 -0.17358909  0.59433735 -0.28215966
  -0.92812991 -1.1702345   0.65420537 -1.18301067]
 [ 0.53828859  1.70699538  0.92738873 -0.13289108 -1.70446737  1.07601538
  -0.90238     1.4200367   1.12150649 -0.87405791]
 [ 0.15167732  0.88700368 -1.19345139 -0.38222296  1.28437961  0.67291762
   1.33747493 -1.90656208 -0.82178666  1.49621374]
 [ 0.78098905  0.18544551  0.46176388  0.87238858 -0.71767704 -0.27333903
   1.13359523 -0.40430751 -0.9583302   0.39854534]
 [-2.31784851  0.74505659  0.55054834  1.83888912  0.46978371  0.48345801
   0.40787767  1.28074404  0.59140289  0.8698563 ]
 [-0.57368894 -0.80151874  0.29699824 -0.36182986  0.62102947  0.74130111
   0.97922237 -1.61029484  0.42438236  0.91514919]
 [ 0.99928742  0.37920381  0.20009187  0.95747427 -1.3764186  -1.03830216
   0.57469107 -0.35981744  0.40066076 -1.98625412]
 [ 0.38063906  0.37949414  0.81477752 -0.56164064  0.39455819  0.35388214
   1.21843591 -1.5811471  -0.19320854 -1.12296242]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [45]:
n = 10
P = np.arange(1,13)
A = np.random.random((10,10))
t_ind = np.random.sample()
np.put(A,np.random.choice(n*n,12,replace=False),P)
print(A)

[[2.89468084e-01 4.18293083e-01 6.57729980e-01 3.25289447e-01
  9.27774833e-01 4.50225436e-01 4.00000000e+00 5.15155816e-01
  6.00000000e+00 6.72699218e-01]
 [6.77607114e-01 3.02102895e-01 2.44567464e-01 6.34799518e-01
  1.76231956e-01 1.60830535e-01 4.89074032e-01 4.89257841e-01
  3.01424785e-01 3.70740548e-03]
 [1.00000000e+00 1.00961365e-01 7.08959642e-01 1.20000000e+01
  7.58699861e-04 8.47613962e-01 5.29433631e-01 8.99114269e-01
  1.10000000e+01 2.75589638e-01]
 [5.81747784e-01 8.50399788e-01 9.37655464e-01 5.76025102e-01
  5.37070316e-01 6.42567650e-01 4.95996256e-01 6.95183835e-01
  5.54905119e-01 4.73054911e-01]
 [7.32734624e-01 2.00000000e+00 2.40686418e-01 8.73816095e-01
  2.99647083e-01 4.69532668e-01 2.79244276e-01 1.00000000e+01
  3.04874451e-01 4.97127887e-01]
 [7.18937967e-01 3.59991022e-01 9.00000000e+00 3.96003246e-01
  5.69010870e-01 8.00000000e+00 3.23585363e-01 4.96070733e-01
  9.39307529e-01 5.23648279e-01]
 [7.62348093e-01 8.17840589e-01 9.56364825e-01 4.78470023e

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [66]:
M = np.arange(100).reshape((10,10)).astype(float)
print(M)
M -= M.mean(axis=1, keepdims=True)
print(M)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
 [50. 51. 52. 53. 54. 55. 56. 57. 58. 59.]
 [60. 61. 62. 63. 64. 65. 66. 67. 68. 69.]
 [70. 71. 72. 73. 74. 75. 76. 77. 78. 79.]
 [80. 81. 82. 83. 84. 85. 86. 87. 88. 89.]
 [90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]]
[[-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
 [-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
 [-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
 [-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
 [-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
 [-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
 [-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
 [-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
 [-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
 [-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]]


#### 59. How to sort an array by the nth column? (★★☆)

In [75]:
Z = np.random.random((10,10))
n = 7
print(Z[Z[:,n].argsort()])

[[0.42573608 0.25219955 0.04420435 0.27457419 0.75402    0.23971852
  0.66558464 0.18583854 0.40704384 0.86834594]
 [0.36505682 0.98284006 0.23120944 0.53464082 0.08932353 0.84362399
  0.32609489 0.35652375 0.54044087 0.75754152]
 [0.95539784 0.73299085 0.07913592 0.06182912 0.59478097 0.24085079
  0.48923356 0.35901853 0.68068981 0.67712533]
 [0.00216702 0.49358802 0.97278621 0.95642478 0.39385803 0.27131006
  0.15054422 0.3661777  0.62218714 0.33930645]
 [0.66367578 0.07097736 0.67192333 0.30126505 0.74918176 0.36687707
  0.42813327 0.47151552 0.73061337 0.26634598]
 [0.9870559  0.40811164 0.11188805 0.6774115  0.64711256 0.79529628
  0.83457688 0.54858021 0.67838051 0.98633494]
 [0.17602788 0.18906794 0.29981499 0.82032537 0.59716039 0.57158442
  0.24218614 0.56775115 0.54119657 0.42401843]
 [0.44185714 0.16358383 0.97378503 0.45638234 0.76136909 0.12516089
  0.99981412 0.69876265 0.87759049 0.3699809 ]
 [0.83451629 0.77638649 0.13485266 0.83042912 0.49489201 0.38730268
  0.97534341

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [90]:
Z = np.random.randint(0,4,(3,10))
print((~Z.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [9]:
Z = np.random.random((10,10))
target = 0.5
print(Z.flat[np.argmin(abs(Z-0.5))])

0.4944540001398223


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [11]:
A = np.random.random((3,1))
B = np.random.random((1,3))
C = (A.T+B).flatten()
D = np.zeros(3)
for i in range(3):
    D[i] = A[i,0] + B[0,i]
print(C)
print(D)

[0.20184757 0.50569952 1.72343676]
[0.20184757 0.50569952 1.72343676]


#### 63. Create an array class that has a name attribute (★★☆)

In [12]:
class NamedArray(np.ndarray):
    def __new__(cls,array,name = "no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self,obj):
        if obj is None: return
        self.name = getattr(obj, 'name', 'no name')

Z = NamedArray(np.arange(10), "range_10")
print(Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [17]:
#If don't want +multiple
A = np.random.random(10)
B = np.random.randint(1,4,3)
A[B] += 1
print(A)
A[B] -= 1
#If want +multiple
np.add.at(A,B,1)
print(A)

[0.32031171 1.5059605  1.98947761 0.67389368 0.62565222 0.19750747
 0.07274582 0.86359907 0.36359344 0.97833104]
[0.32031171 1.5059605  2.98947761 0.67389368 0.62565222 0.19750747
 0.07274582 0.86359907 0.36359344 0.97833104]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [26]:
X = np.random.random(10)
I = np.random.randint(1,4,9)
F = X[I]
print(F)
#or using bincount
F = np.bincount(I,X)
print(F)

[0.90585766 0.43260404 0.43260404 0.43260404 0.79458216 0.43260404
 0.90585766 0.79458216 0.90585766]


ValueError: The weights and list don't have the same length.

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [29]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [32]:
A = np.random.random((2,2,2,2))
print(A.sum(axis=(-2,-1)))
print(A.sum(axis=(-1,-2)))

[[1.24606068 1.34188626]
 [1.72920653 2.38326557]]
[[1.24606068 1.34188626]
 [1.72920653 2.38326557]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [38]:
#Get a weighted average of the entire thing
print(D)
D = np.random.random(100)
S = np.random.randint(0,10,100)
print(D[S].mean())

#Do the actual question
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.82745107 0.94948766 0.82167895 0.73094529 0.41183537 0.922414
 0.5092812  0.51037073 0.97573902 0.08980482]
0.6278946006668125
[0.4772764  0.63675342 0.62706766 0.54502996 0.58451959 0.58599597
 0.61857303 0.51479343 0.46558222 0.47678954]


#### 69. How to get the diagonal of a dot product? (★★★)

In [41]:
A = np.random.random((10,2))
B = np.random.random((2,3))
print(np.diag(np.dot(A,B)))


[0.2420857  0.31178562 0.17401927]


ValueError: operands could not be broadcast together with shapes (10,2) (3,2) 

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [44]:
A = np.arange(1,6)
B = np.zeros(20)
B[::4] = A
print(B)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [50]:
A = np.random.random((2,2,3))
B = np.random.random((2,2))
print(A * B[:,:,None])
print(A * B[:,:,np.newaxis])

[[[0.01129937 0.18514801 0.16621995]
  [0.4219501  0.35741216 0.52955757]]

 [[0.08556862 0.19543784 0.00932649]
  [0.00950302 0.01350425 0.00333946]]]
Second attempt:
[[[0.01129937 0.18514801 0.16621995]
  [0.4219501  0.35741216 0.52955757]]

 [[0.08556862 0.19543784 0.00932649]
  [0.00950302 0.01350425 0.00333946]]]


#### 72. How to swap two rows of an array? (★★★)

In [53]:
A = np.random.random((2,2))
print(A)
A[:,[0,1]] = A[:,[1,0]]
print(A)

[[0.04904723 0.16490745]
 [0.0175906  0.40176762]]
[[0.16490745 0.04904723]
 [0.40176762 0.0175906 ]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [54]:
#Not completed

[[94 87 14]
 [87 97  3]
 [96 57 95]
 [24 54 19]
 [69 57 15]
 [19 75 87]
 [40 33 64]
 [85 55 25]
 [81 29 13]
 [90 40 80]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [61]:
C = np.random.randint(0,3,10)
print(C)
A = np.repeat(np.arange(10),C)
print(A)

[2 2 0 1 2 0 2 2 2 0]
[0 0 1 1 3 4 4 6 6 7 7 8 8]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [67]:
A = np.arange(1,11)

def moving_average(array, n=3):
    ret = np.cumsum(array)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n-1:] / n

print(moving_average(A,3))
from numpy.lib.stride_tricks import sliding_window_view
print(sliding_window_view(A,3).mean(axis=-1))

[2. 3. 4. 5. 6. 7. 8. 9.]
[2. 3. 4. 5. 6. 7. 8. 9.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [68]:
from numpy.lib.stride_tricks import sliding_window_view
A = np.arange(1,11)
print(sliding_window_view(A,3))

[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [70]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.15732894,  0.72640988, -0.87849537, -0.62166788, -0.40419258,
        0.42996621,  0.7470102 , -0.17324626,  0.92679514,  0.78868853,
        0.53503105,  0.34368234,  0.13395479,  0.8469183 , -0.50181204,
        0.0958917 , -0.06254007, -0.42393569, -0.78607033, -0.14085026,
       -0.88222491,  0.8151084 , -0.34067086, -0.20842194,  0.27217954,
       -0.63642056,  0.15552092, -0.88903815,  0.31577533,  0.73781845,
        0.87008455,  0.29661592,  0.13146122,  0.27969726, -0.40819862,
       -0.67458978, -0.04355612, -0.48779562,  0.66244151, -0.26888761,
       -0.43075848, -0.42538153, -0.13990134,  0.1630368 ,  0.18908119,
       -0.61660581, -0.95832759, -0.62023218, -0.58480172,  0.98110282,
        0.17330509, -0.41058312,  0.45285241, -0.05983215,  0.83137568,
        0.06326372, -0.77728137,  0.84920676, -0.10218433, -0.91808413,
       -0.731088  , -0.16420359,  0.2941301 ,  0.95966084,  0.61632738,
       -0.63098307, -0.57569599, -0.62618374, -0.93597062, -0.16

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
#skipped
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [77]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    P_reshaped = P[:] if P.ndim == 2 else P
    U = -np.sum((P0 - P_reshaped) * T, axis=1, keepdims=True) / L
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
P  = np.random.uniform(-10,10,(10,2))
print(distance(P0, P1, P))

ValueError: operands could not be broadcast together with shapes (10,10) (10,2) 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [78]:
Z = np.arange(1,15)
print(sliding_window_view(Z,4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [98]:
A = np.random.randint(0,2,(2,2))
print(A)
print(np.linalg.matrix_rank(A))

[[1 1]
 [1 0]]
2


#### 83. How to find the most frequent value in an array?

In [142]:
A = np.random.randint(0,2,(5,2))
print(A)
np.bincount(A.flat).argmax()

[[1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]]


1

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [144]:
A = np.random.random((3,3))
print(A)
print(sliding_window_view(A,(2,2)))

[[0.11334663 0.56042743 0.51012466]
 [0.56890676 0.59637739 0.52176009]
 [0.63994474 0.48250651 0.08743736]]
[[[[0.11334663 0.56042743]
   [0.56890676 0.59637739]]

  [[0.56042743 0.51012466]
   [0.59637739 0.52176009]]]


 [[[0.56890676 0.59637739]
   [0.63994474 0.48250651]]

  [[0.59637739 0.52176009]
   [0.48250651 0.08743736]]]]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [149]:
# class Symmetric(np.ndarray):
#     def __new__(cls,array):
#         obj = np.asarray(array).view(cls)
#         shape = array.shape[0]
#         print(shape)
#         print(np.triu_indices(shape, k=1))
#         obj[np.triu_indices(shape, k=1)] = obj[np.tril_indices(shape, k=1)]
#         return obj
    
# A = Symmetric(np.random.random((2,2)))
# print(A)

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)
S[2,3] = 12
print(S)
    

[[ 7  8  4  2  5]
 [ 8  3 17  9 10]
 [ 4 17  7 42  6]
 [ 2  9 42  6  7]
 [ 5 10  6  7  2]]
[[ 7  8  4  2  5]
 [ 8  3 17  9 10]
 [ 4 17  7 12  6]
 [ 2  9 12  6  7]
 [ 5 10  6  7  2]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [155]:
p,n = 10,20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M,V,axes = [[0,2], [0,1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [159]:
Z = np.random.random(100)
Z ** 3
np.power(Z,3,out=Z)

array([7.52719576e-01, 2.34336107e-02, 2.08302775e-01, 1.26238025e-04,
       3.52656593e-01, 7.41787263e-03, 1.42834076e-03, 6.42427809e-03,
       6.17713961e-03, 1.13800035e-01, 6.54369359e-01, 2.00793251e-06,
       3.37924687e-01, 4.64094803e-02, 3.96994123e-01, 4.79015901e-01,
       1.56734217e-02, 3.09288570e-01, 8.19160374e-02, 2.48884574e-01,
       4.16012997e-01, 4.67217963e-01, 7.84261004e-01, 1.48662444e-01,
       8.22384505e-02, 1.20190356e-02, 2.15291051e-02, 1.63727358e-02,
       9.08491033e-07, 1.80635993e-01, 1.11160863e-01, 1.34902338e-03,
       2.61075042e-04, 1.70250802e-02, 1.86747189e-01, 3.40224058e-01,
       6.11197689e-02, 1.46890922e-04, 4.78288304e-01, 1.96188429e-01,
       1.70776301e-01, 3.83648708e-01, 2.41066839e-01, 3.29924471e-01,
       1.98785795e-03, 1.53105634e-02, 8.25230798e-01, 4.51709874e-02,
       4.90000034e-02, 3.64727535e-03, 5.81354226e-02, 1.96841435e-01,
       5.80119148e-02, 3.74549072e-01, 4.81581827e-01, 4.85455739e-02,
      

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)